title: Henry Choi # your name (or website title) here
logo: "/images/htchoi.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am currently pursuing a Master's in Analytics with a specialization in Computational Data.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/henrychoi913">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-KRL3ZWMSFG # your Google Analytics tracking ID here
